# Generated by Django 6.0.1

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=255)),
                ('tipo', models.CharField(choices=[('CODIGO', 'Código / Lei'), ('MINUTA', 'Minuta'), ('JURISPRUDENCIA', 'Jurisprudência'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('arquivo', models.FileField(upload_to='documentos_area/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('content', martor.models.MartorField(blank=True, default='')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.areaatuacao')),
            ],
        ),
    ]
