# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pergunta',
            old_name='texto',
            new_name='pergunta',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='resposta',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='criada_em',
        ),
    ]
