# Generated by Django 6.0.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('ia', '0004_add_analise_jurisprudencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.areaatuacao')),
            ],
        ),
        migrations.CreateModel(
            name='ContextRagArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('tool_name', models.CharField(max_length=255)),
                ('tool_args', models.JSONField(blank=True, null=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ia.perguntaarea')),
            ],
        ),
    ]
