# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0005_perguntaarea_contextragarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='resposta',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='perguntaarea',
            name='resposta',
            field=models.TextField(blank=True, default=''),
        ),
    ]
