# Generated by Django 6.0.1 on 2026-02-08 12:26

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_documentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='content',
            field=martor.models.MartorField(blank=True, default=''),
        ),
    ]
