# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_documentos_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
