# Generated by Django 6.0.1

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0005_honorario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total do processo a receber', max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='honorario',
            name='data_vencimento',
            field=models.DateField(blank=True, help_text='Data de vencimento do boleto (para identificar boletos em atraso)', null=True),
        ),
        migrations.AddField(
            model_name='honorario',
            name='processo',
            field=models.ForeignKey(blank=True, help_text='Processo associado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.processo'),
        ),
    ]
