# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_add_processo_and_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
